baseURL = 'https://0xcmars.github.io/'
languageCode = 'en-us'
title = '0xCMars Blog'
theme = 'mini'

defaultContentLanguage = 'en'

hasCJKLanguage = true
[permalinks]
  posts = '/posts/:title/'

paginate = '3'

# googleAnalytics = your-google-analytics-id
# disqusShortname = your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
[markup]
  [highlight]
    guessSyntax = true
    style = 'emacs'
  [tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  [goldmark]
    [renderer]
      unsafe = true

# Social links in footer, support github,twitter,stackoverflow,facebook
[social]
  # e.g.
  github = 'https://github.com/0xCMars'
  twitter = 'https://twitter.com/CMars6667'


# Site parameters
[params]
  # Site Author
  author = 'Author'
  # Author biography
  bio = 'Engineer | Curious'
  # Site Description, used in HTML meat
  description = '0xCMars Blog'
  enableRSS = true
  enableComments = false
  enableGoogleAnalytics = false
